### ISSUE TITLE
I can't enter the server

### ISSUE THREAD

**Issue by Drag0nst** [PieMC-Dev/PieMC#23]

**Comment by andiricum2** [comment]
Hi @Drag0nst, PieMC is currently under development, you have the development process in the readme.md. If you want to find out about all the news, we recommend that you enter our discord server: https://discord.gg/ybXKzdyNhG
You can also be part of the development team: https://piemc-dev.github.io/developers

**Comment by skyss0fly** [comment]
pinned until it is no longer needed:)

**Comment by Amitminer** [comment]
👍
