### ISSUE TITLE
ModuleNotFoundError: No module named 'pieraknet'

### ISSUE THREAD

**Issue by thedrewen** [PieMC-Dev/PieMC#48]
Hello, I'm trying to start piemc on linux and here's my error:
ModuleNotFoundError: No module named 'pieraknet'

**Comment by andiricum2** [comment]
Hi @thedrewen First of all, explain to you that even if you can start PieMC you will not be able to connect with your client, this is because PieMC is still in development. On the other hand, if you want to run PieMC you can install the requirements with pip install -r requirements, even if you still get the error, use pip install piebedrock and pip install pieraknet

Have a nice day :)

**Comment by SixpennyYard** [comment]
Their is an issue with PieRakNet. Even if we run pip install PieRakNet or -r requirement.txt it do not work. In fact it don't istall the code... don't know why.. 
To solve this issue I downloaded it manualy and moved it in the right folder. Here is the link: https://github.com/PieMC-Dev/PieRakNet

**Comment by andiricum2** [comment]
Ok, thanks for letting us know, we will try to solve it as soon as possible

**Comment by andiricum2** [comment]
Hi @SixpennyYard, I can install Pieraknet properly, can you try again please. 
![image](https://github.com/PieMC-Dev/PieMC/assets/62946099/4dccbab9-e721-461c-b3f5-38ea1e57c90b)

**Comment by andiricum2** [comment]
I install Pieknet correctly. Can you send me more information about your Python version please?

![image](https://github.com/PieMC-Dev/PieMC/assets/62946099/992c448b-cb48-41dc-805e-daeb2ef39f6a)
![image](https://github.com/PieMC-Dev/PieMC/assets/62946099/c23e1387-1405-4588-a2ee-20872f489495)

**Comment by SixpennyYard** [comment]
Sure, here are the informations: 
![image](https://github.com/PieMC-Dev/PieMC/assets/88838512/c49cdbec-326d-4f11-b435-57cacf7b9e80)

**Comment by andiricum2** [comment]
I dont know why is happening that, ill investigate

**Comment by andiricum2** [comment]
We just released a new version of PieRakNet! (https://github.com/PieMC-Dev/PieRakNet/commit/4ebc9cbd5cdcb49318a0aca66ca3789657a9b661)

Try installing it with ```pip install pieraknet``` or with ```pip install git+https://github.com/PieMC-Dev/PieRakNet.git```

Let me know if it works for you or not,

Thanks 😇

**Comment by SixpennyYard** [comment]
It works, well done ! Let's start working on it..

**Comment by skyss0fly-pm-pl** [comment]
Issue resolved? Closing issue?

**Comment by SixpennyYard** [comment]
> Issue resolved? Closing issue?

Yes, thank you
